export const columns = [
  { id: "mf_id", columnKey: "ManufacturerId", label: "Manufacturer Id" },
  {
    id: "mf_catlog",
    columnKey: "ManufacturerCatalogNumber",
    label: "MCN",
  },
  {
    id: "item_desc",
    columnKey: "ItemDescription",
    label: "Item Description",
  },
  { id: "company", columnKey: "Company", label: "Company" },
  { id: "group", columnKey: "Group", label: "Group" },
  { id: "business", columnKey: "Business", label: "Business" },
  { id: "division", columnKey: "Division", label: "Division" },
  { id: "therapy", columnKey: "Therapy", label: "Therapy" },
  { id: "specialty", columnKey: "Specialty", label: "Specialty" },
  { id: "anatomy", columnKey: "Anatomy", label: "Anatomy" },
  { id: "sub_anatomy", columnKey: "SubAnatomy", label: "SubAnatomy" },
  {
    id: "prod_category",
    columnKey: "ProductCategory",
    label: "ProductCategory",
  },
  { id: "prod_family", columnKey: "ProductFamily", label: "ProductFamily" },
  { id: "model", columnKey: "Model", label: "Model" },
  { id: "prod_code", columnKey: "productCode", label: "ProductCode" },
  {
    id: "prod_code_name",
    columnKey: "productCodeName",
    label: "ProductCodeName",
  },
  { id: "comment", columnKey: "comment", label: "Notes" },
  { id: "action", columnKey: "Action", label: "Actions" },
];

export const requiredKeys = [
  "ManufacturerId",
  "ManufacturerCatalogNumber",
  "ItemDescription",
  "Company",
  "Group",
  "Anatomy",
  "Business",
  "Division",
  "Model",
  "ProductCategory",
  "ProductFamily",
  "Specialty",
  "SubAnatomy",
  "Therapy",
  "productCode",
  "productCodeName",
];
