export const clusteredData = {
    "MDT": {
        "{'ManufacturerCatalogNumber': 'SB7JR45', 'ItemDescription': 'CATHETER GUIDING L100CM OD7FR ID0.080IN PEBAX HDPE LINER INNER LUMEN HYDROPHILIC COATED JR4.5 CORONARY SINGLE LUMEN INNER/OUTER JACKET ENCAPSULATED FLAT BRAID WIRE RADIOPAQUE MARKER BAND 3MM FROM TIP SUPERIOR TORQUE CONTROL CURVE RETENTION SOFT TIP FULL WALL TECHNOLOGY STERILE DISPOSABLE SHERPA NX F'}": [
            {
                "ManufacturerId": "457971",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "SB7JR35",
                "ItemDescription": "CATHETER GUIDING L100CM OD7FR ID0.080IN PEBAX HDPE LINER INNER LUMEN HYDROPHILIC COATED JR3.5 CORONARY SINGLE LUMEN INNER/OUTER JACKET ENCAPSULATED FLAT BRAID WIRE RADIOPAQUE MARKER BAND 3MM FROM TIP SUPERIOR TORQUE CONTROL CURVE RETENTION SOFT TIP FULL WALL TECHNOLOGY STERILE DISPOSABLE SHERPA NX F",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Cardiovascular",
                "Business": "Coronary & Peripheral Vascular",
                "Division": "Other",
                "Therapy": "Coronary Artery Disease",
                "Specialty": "Other",
                "Anatomy": "Coronary Arteries",
                "SubAnatomy": "Other",
                "ProductCategory": "Catheter",
                "ProductFamily": "Sherpa",
                "Model": "SB7JR35"
            },
            {
                "ManufacturerId": "457971",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "SB6JR45",
                "ItemDescription": "CATHETER GUIDING L100CM OD6FR ID0.070IN PEBAX HDPE LINER INNER LUMEN HYDROPHILIC COATED JR4.5 CORONARY SINGLE LUMEN INNER/OUTER JACKET ENCAPSULATED FLAT BRAID WIRE RADIOPAQUE MARKER BAND 3MM FROM TIP SUPERIOR TORQUE CONTROL CURVE RETENTION SOFT TIP FULL WALL TECHNOLOGY STERILE DISPOSABLE SHERPA NX F",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Cardiovascular",
                "Business": "Coronary & Peripheral Vascular",
                "Division": "Other",
                "Therapy": "Coronary Artery Disease",
                "Specialty": "Other",
                "Anatomy": "Coronary Arteries",
                "SubAnatomy": "Other",
                "ProductCategory": "Catheter",
                "ProductFamily": "Sherpa",
                "Model": "SB6JR45"
            },
            {
                "ManufacturerId": "457971",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "SB7JR40",
                "ItemDescription": "CATHETER GUIDING L100CM OD7FR ID0.080IN PEBAX HDPE LINER INNER LUMEN HYDROPHILIC COATED JR4 CORONARY SINGLE LUMEN INNER/OUTER JACKET ENCAPSULATED FLAT BRAID WIRE RADIOPAQUE MARKER BAND 3MM FROM TIP SUPERIOR TORQUE CONTROL CURVE RETENTION SOFT TIP FULL WALL TECHNOLOGY STERILE DISPOSABLE SHERPA NX FOR",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Cardiovascular",
                "Business": "Coronary & Peripheral Vascular",
                "Division": "Other",
                "Therapy": "Coronary Artery Disease",
                "Specialty": "Other",
                "Anatomy": "Coronary Arteries",
                "SubAnatomy": "Other",
                "ProductCategory": "Catheter",
                "ProductFamily": "Sherpa",
                "Model": "SB7JR40"
            },
            {
                "ManufacturerId": "457971",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "SB7JR50",
                "ItemDescription": "CATHETER GUIDING L100CM OD7FR ID0.080IN PEBAX HDPE LINER INNER LUMEN HYDROPHILIC COATED JR5 CORONARY SINGLE LUMEN INNER/OUTER JACKET ENCAPSULATED FLAT BRAID WIRE RADIOPAQUE MARKER BAND 3MM FROM TIP SUPERIOR TORQUE CONTROL CURVE RETENTION SOFT TIP FULL WALL TECHNOLOGY STERILE DISPOSABLE SHERPA NX FOR",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "457971",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "SB7JL45",
                "ItemDescription": "CATHETER GUIDING L100CM OD7FR ID0.080IN PEBAX HDPE LINER INNER LUMEN HYDROPHILIC COATED JL4.5 CORONARY SINGLE LUMEN INNER/OUTER JACKET ENCAPSULATED FLAT BRAID WIRE RADIOPAQUE MARKER BAND 3MM FROM TIP SUPERIOR TORQUE CONTROL CURVE RETENTION SOFT TIP FULL WALL TECHNOLOGY STERILE DISPOSABLE SHERPA NX F",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            }
        ],
        "{'ManufacturerCatalogNumber': '00Z2793', 'ItemDescription': 'BYPASS KITS'}": [
            {
                "ManufacturerId": "517863",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "00Z2273",
                "ItemDescription": "BYPASS KIT",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "517863",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "00Z2753",
                "ItemDescription": "KIT LAP GASTRIC BYPASS",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "517863",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "00Z2787",
                "ItemDescription": "KIT BARIATRIC BYPASS",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Neuroscience",
                "Business": "Specialty Therapies",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Bariatric Surgery",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "517863",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "00Z2973",
                "ItemDescription": "KIT LAP GASTRIC BYPASS/ Z2232",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "517863",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "00Z2232",
                "ItemDescription": "* KIT LAP GASTRIC BYPASS",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ProductCategory": "Vascular catheter introduction set, nonimplantable",
                "gmdnPTDefinition": "A collection of sterile, nonimplantable, invasive devices intended to provide percutaneous vascular access to enable introduction of a catheter (not included) into the vascular system. It includes a non-steerable introducer sheath with an inner obturator/dilator, and typically an additional access device(s) [e.g., guidewire, introducer needle, syringe, additional dilators] which may include a haemostatic valve to control blood loss, usually to enable arterial access. This is a single-use device.",
                "ProductFamily": "INPUT\u2122 PS",
                "ManufacturerCatalogNumber": "060023",
                "companyName": "MEDTRONIC, INC.",
                "ItemDescription": "INTRDCR 060023 5PK 6F 23CM INPT INTR KIT",
                "productCode": "DYB",
                "productCodeName": "INTRODUCER, CATHETER",
                "Model": "060023"
            },
            {
                "ProductCategory": "Vascular catheter introduction set, nonimplantable",
                "gmdnPTDefinition": "A collection of sterile, nonimplantable, invasive devices intended to provide percutaneous vascular access to enable introduction of a catheter (not included) into the vascular system. It includes a non-steerable introducer sheath with an inner obturator/dilator, and typically an additional access device(s) [e.g., guidewire, introducer needle, syringe, additional dilators] which may include a haemostatic valve to control blood loss, usually to enable arterial access. This is a single-use device.",
                "ProductFamily": "INPUT\u2122 PS",
                "ManufacturerCatalogNumber": "060023",
                "companyName": "MEDTRONIC, INC.",
                "ItemDescription": "INTRDCR 060023 5PK 6F 23CM INPT INTR KIT",
                "productCode": "DYB",
                "productCodeName": "INTRODUCER, CATHETER",
                "Model": "060023"
            },
            {
                "ProductCategory": "Non-woven gauze pad",
                "gmdnPTDefinition": "A non-medicated device in the form of a patch or swab (also referred to as a sponge) made from non-woven material (e.g., rayon/polyester) and primarily designed to absorb fluids for medical purposes. It is typically used to cover/clean wounds or abrasions and absorb their exudates, absorb body-surface exudates, or to apply topical medications; it is intended to produce less lint and be less adherent than basic woven gauze pads; it does not include petrolatum. This is a single-use device.",
                "ProductFamily": "MEROCEL\u00ae",
                "ManufacturerCatalogNumber": "400423",
                "companyName": "MEDTRONIC XOMED, INC.",
                "ItemDescription": "PACKING 400423 10PK TOFFEL SINUS-PAK KIT",
                "productCode": "EFQ",
                "productCodeName": "GAUZE/SPONGE, INTERNAL",
                "Model": "400423"
            },
            {
                "ProductCategory": "Non-woven gauze pad",
                "gmdnPTDefinition": "A non-medicated device in the form of a patch or swab (also referred to as a sponge) made from non-woven material (e.g., rayon/polyester) and primarily designed to absorb fluids for medical purposes. It is typically used to cover/clean wounds or abrasions and absorb their exudates, absorb body-surface exudates, or to apply topical medications; it is intended to produce less lint and be less adherent than basic woven gauze pads; it does not include petrolatum. This is a single-use device.",
                "ProductFamily": "MEROCEL\u00ae",
                "ManufacturerCatalogNumber": "400423",
                "companyName": "MEDTRONIC XOMED, INC.",
                "ItemDescription": "PACKING 400423 10PK TOFFEL SINUS-PAK KIT",
                "productCode": "NAB",
                "productCodeName": "Gauze / sponge,nonresorbable for external use",
                "Model": "400423"
            },
            {
                "ProductCategory": "Non-woven gauze pad",
                "gmdnPTDefinition": "A non-medicated device in the form of a patch or swab (also referred to as a sponge) made from non-woven material (e.g., rayon/polyester) and primarily designed to absorb fluids for medical purposes. It is typically used to cover/clean wounds or abrasions and absorb their exudates, absorb body-surface exudates, or to apply topical medications; it is intended to produce less lint and be less adherent than basic woven gauze pads; it does not include petrolatum. This is a single-use device.",
                "ProductFamily": "MEROCEL\u00ae",
                "ManufacturerCatalogNumber": "400423",
                "companyName": "MEDTRONIC XOMED, INC.",
                "ItemDescription": "PACKING 400423 10PK TOFFEL SINUS-PAK KIT",
                "productCode": "EFQ",
                "productCodeName": "GAUZE/SPONGE, INTERNAL",
                "Model": "400423"
            }
        ],
        "{'ManufacturerCatalogNumber': '476652', 'ItemDescription': 'SCREW SPNL L14MM DIA4.5MM OCCIPITOCERVICAL UP THOR INFIN'}": [
            {
                "ManufacturerId": "398065",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "407665",
                "ItemDescription": "LEAD PACEMAKER IMPLANTABLE CAPSUREFIX NOVUS TRANSVENOUS VENTRICULAR/ATRIAL SCREW-IN BIPOLAR 65CM",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Cardiovascular",
                "Business": "Cardiac Rhythm And Heart Failure",
                "Division": "Other",
                "Therapy": "Bradycardia",
                "Specialty": "Other",
                "Anatomy": "Heart",
                "SubAnatomy": "Other",
                "ProductCategory": "Pacing System",
                "ProductFamily": "CapSureFix",
                "Model": "-"
            },
            {
                "ManufacturerId": "440845",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "407665",
                "ItemDescription": "LEAD PACEMAKER IMPLANTABLE CAPSUREFIX NOVUS TRANSVENOUS VENTRICULAR/ATRIAL SCREW-IN BIPOLAR 65CM",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Cardiovascular",
                "Business": "Cardiac Rhythm And Heart Failure",
                "Division": "Other",
                "Therapy": "Bradycardia",
                "Specialty": "Other",
                "Anatomy": "Heart",
                "SubAnatomy": "Other",
                "ProductCategory": "Pacing System",
                "ProductFamily": "CapSureFix",
                "Model": "-"
            },
            {
                "ManufacturerId": "398065",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "407652",
                "ItemDescription": "LEAD PACEMAKER IMPLANTABLE CAPSUREFIX NOVUS TRANSVENOUS VENTRICULAR/ATRIAL SCREW-IN BIPOLAR 52CM",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Cardiovascular",
                "Business": "Cardiac Rhythm And Heart Failure",
                "Division": "Other",
                "Therapy": "Bradycardia",
                "Specialty": "Other",
                "Anatomy": "Heart",
                "SubAnatomy": "Other",
                "ProductCategory": "Pacing System",
                "ProductFamily": "CapSureFix",
                "Model": "-"
            },
            {
                "ManufacturerId": "440845",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "407652",
                "ItemDescription": "LEAD PACEMAKER IMPLANTABLE CAPSUREFIX NOVUS TRANSVENOUS VENTRICULAR/ATRIAL SCREW-IN BIPOLAR 52CM",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Cardiovascular",
                "Business": "Cardiac Rhythm And Heart Failure",
                "Division": "Other",
                "Therapy": "Bradycardia",
                "Specialty": "Other",
                "Anatomy": "Heart",
                "SubAnatomy": "Other",
                "ProductCategory": "Pacing System",
                "ProductFamily": "CapSureFix",
                "Model": "-"
            },
            {
                "ManufacturerId": "372300",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "76695525",
                "ItemDescription": "SCREW SPINAL L25MM OD5.5MM STAINLESS STEEL THORACOLUMBOSACRAL PEDICLE ANTERIOR/POSTERIOR PERCUTANEOUS APPROACH FULLY THREADED VARIABLE ANGLE REDUCTION SINGLE LEAD THREAD PATTERN BUTTRESS NONSTERILE CYLINDRICAL IMPLANTABLE CD HORIZON LEGACY FOR 6.35MM MINI",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ProductCategory": "Bone-screw internal spinal fixation system, non-sterile",
                "gmdnPTDefinition": "An assembly of non-sterile implantable devices intended to provide immobilization and stabilization of spinal segments in the treatment of various spinal instabilities or deformities, also used as an adjunct to spinal fusion [e.g., for degenerative disc disease (DDD)]. Otherwise known as a pedicle screw instrumentation system, it typically consists of a combination of anchors (e.g., bolts, hooks, pedicle screws or other types), interconnection mechanisms (incorporating nuts, screws, sleeves, or bolts), longitudinal members (e.g., plates, rods, plate/rod combinations), and/or transverse connectors. Non-sterile disposable devices associated with implantation may be included.",
                "ProductFamily": "CD HORIZON\u00ae Spinal System",
                "ManufacturerCatalogNumber": "76446520",
                "companyName": "MEDTRONIC SOFAMOR DANEK, INC.",
                "ItemDescription": "SCREW 76446520 6.5 X 20MM MULTI AXIAL TI",
                "productCode": "KWP",
                "productCodeName": "APPLIANCE, FIXATION, SPINAL INTERLAMINAL",
                "Model": "76446520"
            },
            {
                "ProductCategory": "Bone-screw internal spinal fixation system, non-sterile",
                "gmdnPTDefinition": "An assembly of non-sterile implantable devices intended to provide immobilization and stabilization of spinal segments in the treatment of various spinal instabilities or deformities, also used as an adjunct to spinal fusion [e.g., for degenerative disc disease (DDD)]. Otherwise known as a pedicle screw instrumentation system, it typically consists of a combination of anchors (e.g., bolts, hooks, pedicle screws or other types), interconnection mechanisms (incorporating nuts, screws, sleeves, or bolts), longitudinal members (e.g., plates, rods, plate/rod combinations), and/or transverse connectors. Non-sterile disposable devices associated with implantation may be included.",
                "ProductFamily": "CD HORIZON\u00ae Spinal System",
                "ManufacturerCatalogNumber": "76446520",
                "companyName": "MEDTRONIC SOFAMOR DANEK, INC.",
                "ItemDescription": "SCREW 76446520 6.5 X 20MM MULTI AXIAL TI",
                "productCode": "KWQ",
                "productCodeName": "APPLIANCE, FIXATION, SPINAL INTERVERTEBRAL BODY",
                "Model": "76446520"
            },
            {
                "ProductCategory": "Bone-screw internal spinal fixation system, non-sterile",
                "gmdnPTDefinition": "An assembly of non-sterile implantable devices intended to provide immobilization and stabilization of spinal segments in the treatment of various spinal instabilities or deformities, also used as an adjunct to spinal fusion [e.g., for degenerative disc disease (DDD)]. Otherwise known as a pedicle screw instrumentation system, it typically consists of a combination of anchors (e.g., bolts, hooks, pedicle screws or other types), interconnection mechanisms (incorporating nuts, screws, sleeves, or bolts), longitudinal members (e.g., plates, rods, plate/rod combinations), and/or transverse connectors. Non-sterile disposable devices associated with implantation may be included.",
                "ProductFamily": "CD HORIZON\u00ae Spinal System",
                "ManufacturerCatalogNumber": "76446520",
                "companyName": "MEDTRONIC SOFAMOR DANEK, INC.",
                "ItemDescription": "SCREW 76446520 6.5 X 20MM MULTI AXIAL TI",
                "productCode": "MNI",
                "productCodeName": "ORTHOSIS, SPINAL PEDICLE FIXATION",
                "Model": "76446520"
            },
            {
                "ProductCategory": "Bone-screw internal spinal fixation system, non-sterile",
                "gmdnPTDefinition": "An assembly of non-sterile implantable devices intended to provide immobilization and stabilization of spinal segments in the treatment of various spinal instabilities or deformities, also used as an adjunct to spinal fusion [e.g., for degenerative disc disease (DDD)]. Otherwise known as a pedicle screw instrumentation system, it typically consists of a combination of anchors (e.g., bolts, hooks, pedicle screws or other types), interconnection mechanisms (incorporating nuts, screws, sleeves, or bolts), longitudinal members (e.g., plates, rods, plate/rod combinations), and/or transverse connectors. Non-sterile disposable devices associated with implantation may be included.",
                "ProductFamily": "CD HORIZON\u00ae Spinal System",
                "ManufacturerCatalogNumber": "76446520",
                "companyName": "MEDTRONIC SOFAMOR DANEK, INC.",
                "ItemDescription": "SCREW 76446520 6.5 X 20MM MULTI AXIAL TI",
                "productCode": "MNH",
                "productCodeName": "Orthosis, spondylolisthesis spinal fixation",
                "Model": "76446520"
            },
            {
                "ProductCategory": "Bone-screw internal spinal fixation system, non-sterile",
                "gmdnPTDefinition": "An assembly of non-sterile implantable devices intended to provide immobilization and stabilization of spinal segments in the treatment of various spinal instabilities or deformities, also used as an adjunct to spinal fusion [e.g., for degenerative disc disease (DDD)]. Otherwise known as a pedicle screw instrumentation system, it typically consists of a combination of anchors (e.g., bolts, hooks, pedicle screws or other types), interconnection mechanisms (incorporating nuts, screws, sleeves, or bolts), longitudinal members (e.g., plates, rods, plate/rod combinations), and/or transverse connectors. Non-sterile disposable devices associated with implantation may be included.",
                "ProductFamily": "CD HORIZON\u00ae Spinal System",
                "ManufacturerCatalogNumber": "7663525",
                "companyName": "MEDTRONIC SOFAMOR DANEK, INC.",
                "ItemDescription": "SCREW 7663525 FIXED ANGLE 5.5X25 SS",
                "productCode": "MNH",
                "productCodeName": "Orthosis, spondylolisthesis spinal fixation",
                "Model": "7663525"
            }
        ],
        "{'ManufacturerCatalogNumber': 'MR87BA50DFL', 'ItemDescription': 'TOOL MR8 7CM BALL DIAMOND FINE LONG 5MM'}": [
            {
                "ManufacturerId": "451932",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "MR87BA50DF",
                "ItemDescription": "TOOL MR8 7CM BALL DIAMOND FINE 5MM",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Neuroscience",
                "Business": "Cranial and Spinal Technologies",
                "Division": "Other",
                "Therapy": "Neurosurgery",
                "Specialty": "Other",
                "Anatomy": "Mutiple",
                "SubAnatomy": "Other",
                "ProductCategory": "Surgical Instruments",
                "ProductFamily": "Midas Rex",
                "Model": "-"
            },
            {
                "ManufacturerId": "451932",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "MR87BA10DFL",
                "ItemDescription": "TOOL MR8 7CM BALL DIAMOND LONG FINE",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Neuroscience",
                "Business": "Cranial and Spinal Technologies",
                "Division": "Other",
                "Therapy": "Neurosurgery",
                "Specialty": "Other",
                "Anatomy": "Mutiple",
                "SubAnatomy": "Other",
                "ProductCategory": "Surgical Instruments",
                "ProductFamily": "Midas Rex",
                "Model": "-"
            },
            {
                "ManufacturerId": "451932",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "MR87BA15DFL",
                "ItemDescription": "TOOL MR8 7CM BALL DIAMOND LONG FINE",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Neuroscience",
                "Business": "Cranial and Spinal Technologies",
                "Division": "Other",
                "Therapy": "Neurosurgery",
                "Specialty": "Other",
                "Anatomy": "Mutiple",
                "SubAnatomy": "Other",
                "ProductCategory": "Surgical Instruments",
                "ProductFamily": "Midas Rex",
                "Model": "-"
            },
            {
                "ManufacturerId": "451932",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "MR87BA20DFL",
                "ItemDescription": "TOOL MR8 7CM BALL DIAMOND LONG FINE",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Neuroscience",
                "Business": "Cranial and Spinal Technologies",
                "Division": "Other",
                "Therapy": "Neurosurgery",
                "Specialty": "Other",
                "Anatomy": "Mutiple",
                "SubAnatomy": "Other",
                "ProductCategory": "Surgical Instruments",
                "ProductFamily": "Midas Rex",
                "Model": "-"
            },
            {
                "ManufacturerId": "451932",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "MR87BA30DFL",
                "ItemDescription": "TOOL MR8 7CM BALL DIAMOND LONG FINE",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Neuroscience",
                "Business": "Cranial and Spinal Technologies",
                "Division": "Other",
                "Therapy": "Neurosurgery",
                "Specialty": "Other",
                "Anatomy": "Mutiple",
                "SubAnatomy": "Other",
                "ProductCategory": "Surgical Instruments",
                "ProductFamily": "Midas Rex",
                "Model": "-"
            }
        ],
        "{'ManufacturerCatalogNumber': '7Z85R1', 'ItemDescription': 'PACK MYOTHERM INVOCARDIO CUSTOM 7Z85R1'}": [
            {
                "ManufacturerId": "457971",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "HY7F85R17",
                "ItemDescription": "PERFUSION CUSTOM PACK HY7F85R12",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "517863",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "HY7F85R16",
                "ItemDescription": "PERFUSION CUSTOM PACK HY7F85R12",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "457971",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "TL7F85R1",
                "ItemDescription": "PACK CUSTOM OSF ROBOT-EA/1",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "457971",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "BB7H85R11",
                "ItemDescription": "Pack  Custom Large Main (PERFUSION)",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "457971",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "7H81R1",
                "ItemDescription": "CUSTOM PACK TUBING HLDR",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            }
        ],
        "{'ManufacturerCatalogNumber': 'AC0006', 'ItemDescription': 'Medtronic Coronary - AC0006'}": [
            {
                "ManufacturerId": "457971",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "AC0004",
                "ItemDescription": "Medtronic Coronary - AC0004",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "457971",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "CB77006",
                "ItemDescription": "Medtronic Coronary - CB77006",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "394710",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "AC0004",
                "ItemDescription": "Medtronic Neuromodulation - AC0004",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "394710",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "AC0010",
                "ItemDescription": "Medtronic Neuromodulation - AC0010",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "517863",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "AC0019",
                "ItemDescription": "Medtronic Neuromodulation - AC0019",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            }
        ],
        "{'ManufacturerCatalogNumber': 'CB10A89R2', 'ItemDescription': 'PACK CUST 1/4 ECC'}": [
            {
                "ManufacturerId": "440845",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "CB10A89R1",
                "ItemDescription": "PACK CUST 1/4 ECC",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "457971",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "CB10A89R1",
                "ItemDescription": "1/4\" TUBING PACK",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "451932",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "HY10T89R2",
                "ItemDescription": "PACK PERFUSION ECC 3/8",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "451932",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "CB11J10R2",
                "ItemDescription": "PACK ECMO CUST",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "451932",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "CB10A92R4",
                "ItemDescription": "PACK CUST PRFSH CB10A92R",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ProductCategory": "Cardiopulmonary bypass system blood tubing set",
                "gmdnPTDefinition": "A collection of sterile devices including tubing and typically clamps, filters, connectors, and stopcocks, used in a circuit for a cardiopulmonary bypass procedure. The tubing is typically polymeric and may be heparin coated. It is typically used in the blood pump head of a cardiopulmonary bypass system. The tubing, when used in a roller type pump, will be cyclically compressed by the blood pump to cause the blood to flow through the heart-lung bypass system. This is a single-use device.",
                "ProductFamily": null,
                "ManufacturerCatalogNumber": "CB10A89R1",
                "companyName": "MEDTRONIC, INC.",
                "ItemDescription": "CUSTOM PACK CB10A89R1 1/4 ECC",
                "productCode": "DTZ",
                "productCodeName": "OXYGENATOR, CARDIOPULMONARY BYPASS",
                "Model": "CB10A89R1"
            },
            {
                "ProductCategory": "Cardiopulmonary bypass system blood tubing set",
                "gmdnPTDefinition": "A collection of sterile devices including tubing and typically clamps, filters, connectors, and stopcocks, used in a circuit for a cardiopulmonary bypass procedure. The tubing is typically polymeric and may be heparin coated. It is typically used in the blood pump head of a cardiopulmonary bypass system. The tubing, when used in a roller type pump, will be cyclically compressed by the blood pump to cause the blood to flow through the heart-lung bypass system. This is a single-use device.",
                "ProductFamily": null,
                "ManufacturerCatalogNumber": "CB10A89R3",
                "companyName": "MEDTRONIC, INC.",
                "ItemDescription": "CUSTOM PACK CB10A89R3 1/4 ECC",
                "productCode": "DTZ",
                "productCodeName": "OXYGENATOR, CARDIOPULMONARY BYPASS",
                "Model": "CB10A89R3"
            },
            {
                "ProductCategory": "Cardiopulmonary bypass system blood tubing set",
                "gmdnPTDefinition": "A collection of sterile devices including tubing and typically clamps, filters, connectors, and stopcocks, used in a circuit for a cardiopulmonary bypass procedure. The tubing is typically polymeric and may be heparin coated. It is typically used in the blood pump head of a cardiopulmonary bypass system. The tubing, when used in a roller type pump, will be cyclically compressed by the blood pump to cause the blood to flow through the heart-lung bypass system. This is a single-use device.",
                "ProductFamily": null,
                "ManufacturerCatalogNumber": "CB10A92R1",
                "companyName": "MEDTRONIC, INC.",
                "ItemDescription": "CUSTOM PACK CB10A92R1 3/8 ECC",
                "productCode": "DTZ",
                "productCodeName": "OXYGENATOR, CARDIOPULMONARY BYPASS",
                "Model": "CB10A92R1"
            },
            {
                "ProductCategory": "Cardiopulmonary bypass system blood tubing set",
                "gmdnPTDefinition": "A collection of sterile devices including tubing and typically clamps, filters, connectors, and stopcocks, used in a circuit for a cardiopulmonary bypass procedure. The tubing is typically polymeric and may be heparin coated. It is typically used in the blood pump head of a cardiopulmonary bypass system. The tubing, when used in a roller type pump, will be cyclically compressed by the blood pump to cause the blood to flow through the heart-lung bypass system. This is a single-use device.",
                "ProductFamily": null,
                "ManufacturerCatalogNumber": "CB10A92R4",
                "companyName": "MEDTRONIC, INC.",
                "ItemDescription": "CUSTOM PACK CB10A92R4 3/8 ECC",
                "productCode": "DTZ",
                "productCodeName": "OXYGENATOR, CARDIOPULMONARY BYPASS",
                "Model": "CB10A92R4"
            },
            {
                "ProductCategory": "Cardiopulmonary bypass system blood tubing set",
                "gmdnPTDefinition": "A collection of sterile devices including tubing and typically clamps, filters, connectors, and stopcocks, used in a circuit for a cardiopulmonary bypass procedure. The tubing is typically polymeric and may be heparin coated. It is typically used in the blood pump head of a cardiopulmonary bypass system. The tubing, when used in a roller type pump, will be cyclically compressed by the blood pump to cause the blood to flow through the heart-lung bypass system. This is a single-use device.",
                "ProductFamily": null,
                "ManufacturerCatalogNumber": "CB10Y89R13",
                "companyName": "MEDTRONIC, INC.",
                "ItemDescription": "CUSTOM PACK CB10Y89R13 ECC 3/8 A/V",
                "productCode": "DWF",
                "productCodeName": "Catheter, cannula and tubing, vascular, cardiopulmonary bypass",
                "Model": "CB10Y89R13"
            }
        ],
        "{'ManufacturerCatalogNumber': 'CB11G04R5', 'ItemDescription': 'PACK CUSTOM ECMO ECC 3/8 ACCESS   CB11G04R5'}": [
            {
                "ManufacturerId": "517863",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "CB11G04R3",
                "ItemDescription": "PACK CUSTOM ECMO ECC 3/8 ACCESS   CB11G04R3",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "517863",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "CB11G04R1",
                "ItemDescription": "PACK CUSTOM ECMO ECC 3/8 ACCESS   CB11G04R1",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "457971",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "CB5G80R15",
                "ItemDescription": "PACK CUSTOM ECMO",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "457971",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "CB11D49R2",
                "ItemDescription": "PACK CUSTOM ECMO NEO 1/4IN SUPPORT CB11D49R2",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "457971",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "CB10F47R4",
                "ItemDescription": "ECMO PACK",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            }
        ],
        "{'ManufacturerCatalogNumber': 'LXMJ44S', 'ItemDescription': 'Sealer/Divider, Nano, 5 mm \u2014 44 cm'}": [
            {
                "ManufacturerId": "517863",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "LXMJ37S",
                "ItemDescription": "Sealer/Divider, Nano, 5 mm \u2014 37 cm",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "517863",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "LXMJ44L",
                "ItemDescription": "LIGASURE XP MARYLAND 44 CM",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            }
        ],
        "{'ManufacturerCatalogNumber': 'B3315609901', 'ItemDescription': 'UNID EXP B33156099-01 TI PERC 6.0 1-3L'}": [
            {
                "ManufacturerId": "372300",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "B3325609901",
                "ItemDescription": "UNID EXP B33256099-01 CC PERC 6.0 1-3L",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "372300",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "B3315559901",
                "ItemDescription": "UNID EXP B33155599-01 TI PERC 5.5 1-3L",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "372300",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "B3315602201",
                "ItemDescription": "UNID B33156022-01 TI PERC 6.0 1-3LV PTSP",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "372300",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "B3325479901",
                "ItemDescription": "UNID EXP B33254799-01 CC PERC 4.75 1-3L",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "372300",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "B3324569901",
                "ItemDescription": "UNID EXP B33245699-01 DUAL 5.5/6.0 CC",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ProductCategory": "Personal device holder, single-use",
                "gmdnPTDefinition": "A portable, flexible device designed to hold a portable medical device (e.g., long-term recorder, portable oxygen equipment, urine collection bag, tracheostoma protector) during ambulation or sleep; it is neither designed to hold an invasive tube/catheter to the skin surface (i.e., not a catheter/tube holder), nor to house and protect a device from damage (i.e., not a rigid case/housing). It is typically designed as a bag, pouch, strap, belt, or clothing. This is a single-use device.",
                "ProductFamily": null,
                "ManufacturerCatalogNumber": "3560019",
                "companyName": "MEDTRONIC, INC.",
                "ItemDescription": "BELT 3560019 ENS ISTIM DISP 1PK GLBL MDR",
                "productCode": "EZW",
                "productCodeName": "Stimulator, electrical, implantable, for incontinence",
                "Model": "3560019"
            },
            {
                "ProductCategory": "Personal device holder, single-use",
                "gmdnPTDefinition": "A portable, flexible device designed to hold a portable medical device (e.g., long-term recorder, portable oxygen equipment, urine collection bag, tracheostoma protector) during ambulation or sleep; it is neither designed to hold an invasive tube/catheter to the skin surface (i.e., not a catheter/tube holder), nor to house and protect a device from damage (i.e., not a rigid case/housing). It is typically designed as a bag, pouch, strap, belt, or clothing. This is a single-use device.",
                "ProductFamily": null,
                "ManufacturerCatalogNumber": "3560019",
                "companyName": "MEDTRONIC, INC.",
                "ItemDescription": "BELT ENS 3560019 ISTIM DISP GLOBAL",
                "productCode": "EZW",
                "productCodeName": "Stimulator, electrical, implantable, for incontinence",
                "Model": "3560019"
            },
            {
                "ProductCategory": "Instrument tray, reusable",
                "gmdnPTDefinition": "A container intended to provide a suitable platform for placing/containing many medical/surgical/dental instruments and related items for use during a clinical procedure; it might, in addition, be used during, but not dedicated to, reprocessing/sterilization procedures. It is a receptacle in one of a variety of designs, typically with moulded positions for placing the instruments; it might include a lid and/or removable identification tags. This is a reusable device.",
                "ProductFamily": "T2 STRATOSPHERE\u2122 Expandable Corpectomy System",
                "ManufacturerCatalogNumber": "4369901",
                "companyName": "MEDTRONIC SOFAMOR DANEK, INC.",
                "ItemDescription": "TRAY 4369901 STRATOS 20-25MM IMPL-INSTR",
                "productCode": "MQP",
                "productCodeName": "Spinal vertebral body replacement device",
                "Model": "4369901"
            },
            {
                "ProductCategory": "Metal/carbide ENT bur, single-use",
                "gmdnPTDefinition": "A small rotary shaft of hard metal (e.g., steel) or carbide, with fluting or cutting planes of various shapes at the working end, designed for incising or removing cartilage and/or bone from the ear, nose, or throat during an ear/nose/throat (ENT) procedure. It is usually power-driven by a rotary handpiece or other powered device. It is typically used in mastoid surgery, frontal sinus surgery, or surgery of the facial nerves. This is a single-use device.",
                "ProductFamily": "ViSAO\u00ae",
                "ManufacturerCatalogNumber": "31153090E",
                "companyName": "MEDTRONIC XOMED, INC.",
                "ItemDescription": "BUR 31153090E VISAO CVD 3MM 90L 15DEG",
                "productCode": "EQJ",
                "productCodeName": "BUR, EAR, NOSE AND THROAT",
                "Model": "31153090E"
            },
            {
                "ProductCategory": "Metal/carbide ENT bur, single-use",
                "gmdnPTDefinition": "A small rotary shaft of hard metal (e.g., steel) or carbide, with fluting or cutting planes of various shapes at the working end, designed for incising or removing cartilage and/or bone from the ear, nose, or throat during an ear/nose/throat (ENT) procedure. It is usually power-driven by a rotary handpiece or other powered device. It is typically used in mastoid surgery, frontal sinus surgery, or surgery of the facial nerves. This is a single-use device.",
                "ProductFamily": "ViSAO\u00ae",
                "ManufacturerCatalogNumber": "31154090E",
                "companyName": "MEDTRONIC XOMED, INC.",
                "ItemDescription": "BUR 31154090E VISAO CVD 4MM 90L 15DEG",
                "productCode": "EQJ",
                "productCodeName": "BUR, EAR, NOSE AND THROAT",
                "Model": "31154090E"
            }
        ],
        "{'ManufacturerCatalogNumber': '587143', 'ItemDescription': 'SPACER CATALYFT PL LONG 7MM'}": [
            {
                "ManufacturerId": "372300",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "45781713",
                "ItemDescription": "SPACER CANCELLOUS 7 X13MM",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "372300",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "87214",
                "ItemDescription": "SPACER ACDF LORDOTIC LG 8MM",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "394710",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "6958714",
                "ItemDescription": "SCR BN 3.5MM 14MM VRTX MX TI T",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Neuroscience",
                "Business": "Cranial and Spinal Technologies",
                "Division": "Other",
                "Therapy": "Spinal Instability",
                "Specialty": "Other",
                "Anatomy": "Occipitocervical And Upper Thoracic Spine",
                "SubAnatomy": "Other",
                "ProductCategory": "Instruments",
                "ProductFamily": "Vertex",
                "Model": "6958714"
            },
            {
                "ManufacturerId": "372300",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "876143",
                "ItemDescription": "DRILL BIT 13MM",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "517863",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "571042",
                "ItemDescription": "CTH THRC ARGL RT 9.3MM 28FR",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Medical Surgical",
                "Business": "Respiratory, Gastrointestinal, & Renal",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Peritoneal Dialysis Catheter",
                "ProductFamily": "Argyle",
                "Model": "8888571042"
            },
            {
                "ProductCategory": "Spinal implant trial",
                "gmdnPTDefinition": "A copy of a final spinal prosthesis, graft, or other implantable spinal device (e.g., may include intervertebral disc prosthesis, spinal cage, spinal hook) used to validate the proper size of the permanent implant required by the patient, to determine its appropriate position, and/or to verify that the implant site has been cut to the proper dimensions. It can be made of metal or plastic. This is a reusable device.",
                "ProductFamily": "Medtronic Resuable Instruments",
                "ManufacturerCatalogNumber": "9874143",
                "companyName": "MEDTRONIC SOFAMOR DANEK, INC.",
                "ItemDescription": "TRIAL 9874143 DOUBLE-ENDED 43MM 45MM",
                "productCode": "KWQ",
                "productCodeName": "APPLIANCE, FIXATION, SPINAL INTERVERTEBRAL BODY",
                "Model": "9874143"
            },
            {
                "ProductCategory": "Bone-screw internal spinal fixation system, non-sterile",
                "gmdnPTDefinition": "An assembly of non-sterile implantable devices intended to provide immobilization and stabilization of spinal segments in the treatment of various spinal instabilities or deformities, also used as an adjunct to spinal fusion [e.g., for degenerative disc disease (DDD)]. Otherwise known as a pedicle screw instrumentation system, it typically consists of a combination of anchors (e.g., bolts, hooks, pedicle screws or other types), interconnection mechanisms (incorporating nuts, screws, sleeves, or bolts), longitudinal members (e.g., plates, rods, plate/rod combinations), and/or transverse connectors. Non-sterile disposable devices associated with implantation may be included.",
                "ProductFamily": "VERTEX\u00ae Reconstruction System",
                "ManufacturerCatalogNumber": "6958714",
                "companyName": "MEDTRONIC SOFAMOR DANEK, INC.",
                "ItemDescription": "SCREW 6958714 3.5 X 14MM MAS",
                "productCode": "KWP",
                "productCodeName": "APPLIANCE, FIXATION, SPINAL INTERLAMINAL",
                "Model": "6958714"
            },
            {
                "ProductCategory": "Spinal implant trial",
                "gmdnPTDefinition": "A copy of a final spinal prosthesis, graft, or other implantable spinal device (e.g., may include intervertebral disc prosthesis, spinal cage, spinal hook) used to validate the proper size of the permanent implant required by the patient, to determine its appropriate position, and/or to verify that the implant site has been cut to the proper dimensions. It can be made of metal or plastic. This is a reusable device.",
                "ProductFamily": "Crescent Spinal System Titanium",
                "ManufacturerCatalogNumber": "6681436",
                "companyName": "MEDTRONIC SOFAMOR DANEK, INC.",
                "ItemDescription": "TRIAL 6681436 CRESCENT TI WD 14MM X 36MM",
                "productCode": "MAX",
                "productCodeName": "Intervertebral fusion device with bone graft, lumbar",
                "Model": "6681436"
            },
            {
                "ProductCategory": "Spinal implant trial",
                "gmdnPTDefinition": "A copy of a final spinal prosthesis, graft, or other implantable spinal device (e.g., may include intervertebral disc prosthesis, spinal cage, spinal hook) used to validate the proper size of the permanent implant required by the patient, to determine its appropriate position, and/or to verify that the implant site has been cut to the proper dimensions. It can be made of metal or plastic. This is a reusable device.",
                "ProductFamily": "Crescent Spinal System Titanium",
                "ManufacturerCatalogNumber": "6681430",
                "companyName": "MEDTRONIC SOFAMOR DANEK, INC.",
                "ItemDescription": "TRIAL 6681430 CRESCENT TI WD 14MM X 30MM",
                "productCode": "MAX",
                "productCodeName": "Intervertebral fusion device with bone graft, lumbar",
                "Model": "6681430"
            },
            {
                "ProductCategory": "Bone-screw internal spinal fixation system, non-sterile",
                "gmdnPTDefinition": "An assembly of non-sterile implantable devices intended to provide immobilization and stabilization of spinal segments in the treatment of various spinal instabilities or deformities, also used as an adjunct to spinal fusion [e.g., for degenerative disc disease (DDD)]. Otherwise known as a pedicle screw instrumentation system, it typically consists of a combination of anchors (e.g., bolts, hooks, pedicle screws or other types), interconnection mechanisms (incorporating nuts, screws, sleeves, or bolts), longitudinal members (e.g., plates, rods, plate/rod combinations), and/or transverse connectors. Non-sterile disposable devices associated with implantation may be included.",
                "ProductFamily": "CD HORIZON\u00ae Spinal System",
                "ManufacturerCatalogNumber": "7571430",
                "companyName": "MEDTRONIC SOFAMOR DANEK, INC.",
                "ItemDescription": "ROD 7571430 5.5MM STRAIGHT 430MM",
                "productCode": "MNI",
                "productCodeName": "ORTHOSIS, SPINAL PEDICLE FIXATION",
                "Model": "7571430"
            }
        ],
        "{'ManufacturerCatalogNumber': 'STB30C4S', 'ItemDescription': 'EP RETRACT STABILIZER'}": [
            {
                "ManufacturerId": "517863",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "TA3048S",
                "ItemDescription": "STAPLER DST TA 1-USE RELOAD",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Medical Surgical",
                "Business": "Surgical Innovations",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Surgical Instruments",
                "ProductFamily": "TA",
                "Model": "TA3048S"
            },
            {
                "ManufacturerId": "517863",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "TA3048S",
                "ItemDescription": "STAPLER RELOADABLE 30-4.8",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Medical Surgical",
                "Business": "Surgical Innovations",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Surgical Instruments",
                "ProductFamily": "TA",
                "Model": "TA3048S"
            },
            {
                "ManufacturerId": "517863",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "USUTA3048S",
                "ItemDescription": "TA30-4.8 SGL USE RELOA TA3048S",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "517863",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "TA3048S",
                "ItemDescription": "STAPLER INTERNAL STAPLE L30XH4.8MM GREEN TITANIUM RELOADABLE DIRECTIONAL STAPLE TECHNOLOGY RUBBER INLAY GRIP DUAL ACTION HANDLE STERILE B SHAPED DST SERIES TA FOR ABDOMINAL GYNECOLOGICAL PEDIATRIC AND THORACIC SURGICAL PROCEDURE",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Medical Surgical",
                "Business": "Surgical Innovations",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Surgical Instruments",
                "ProductFamily": "TA",
                "Model": "TA3048S"
            },
            {
                "ManufacturerId": "372300",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "T34S",
                "ItemDescription": "CANNULA KYPHON DIRECTIONAL 10GA (1EA)",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ProductCategory": "Bone access channel kit",
                "gmdnPTDefinition": "A collection of sterile manual devices intended to create a percutaneous access channel within a vertebral body or other bones (e.g., hand, radius, tibia, calcaneus) prior to the use of an inflatable balloon (e.g., a balloon catheter or balloon tamp) to create a bone space during kyphoplasty/osteoplasty. It typically consists of bone access needles/cannulae, orthopaedic bone wires (Kirschner wires), a drill, and a curette. It is used in orthopaedic surgery, typically under fluoroscopic guidance, to treat a patient diagnosed with compression fractures. This is a single-use device.",
                "ProductFamily": "Kyphon Assist Directional Cannula Size 2",
                "ManufacturerCatalogNumber": "T34S",
                "companyName": "MEDTRONIC SOFAMOR DANEK, INC.",
                "ItemDescription": "INTRODUCER T34S KYPHON DIRECT SIZE 2",
                "productCode": "LXH",
                "productCodeName": "Orthopedic manual surgical instrument",
                "Model": "T34S"
            },
            {
                "ProductCategory": "Implantable electrical stimulation device management software",
                "gmdnPTDefinition": "A software program intended to assist with the management of an implantable electrical stimulator associated with stimulation of the spinal cord, non-auditory peripheral nerves, brain, and/or muscles; it is not intended to manage hearing assistive implants. It may be intended for use in one or more areas of functionality including: 1) configuration of a variety of electrical pulse parameters (e.g., amplitude, frequency, width) for the provision of periodic electrical stimulation; 2) post-implantation visualization; 3) assessment of programming parameters; 4) collection of patient clinical data.",
                "ProductFamily": "SureTune\u2122 4",
                "ManufacturerCatalogNumber": "B36104S",
                "companyName": "MEDTRONIC, INC.",
                "ItemDescription": "SW B36104S SURETUNE4 DBS SERVER",
                "productCode": "QQC",
                "productCodeName": "Brain stimulation programming planning software.",
                "Model": "B36104S"
            },
            {
                "ProductCategory": "Implantable electrical stimulation device management software",
                "gmdnPTDefinition": "A software program intended to assist with the management of an implantable electrical stimulator associated with stimulation of the spinal cord, non-auditory peripheral nerves, brain, and/or muscles; it is not intended to manage hearing assistive implants. It may be intended for use in one or more areas of functionality including: 1) configuration of a variety of electrical pulse parameters (e.g., amplitude, frequency, width) for the provision of periodic electrical stimulation; 2) post-implantation visualization; 3) assessment of programming parameters; 4) collection of patient clinical data.",
                "ProductFamily": "SureTune\u2122 4",
                "ManufacturerCatalogNumber": "B36104S",
                "companyName": "MEDTRONIC, INC.",
                "ItemDescription": "SW B36104S SURETUNE4 DBS SERVER",
                "productCode": "QQC",
                "productCodeName": "Brain stimulation programming planning software.",
                "Model": "B36104S"
            }
        ],
        "{'ManufacturerCatalogNumber': 'AWM0001', 'ItemDescription': 'SonarMed Monitor'}": [
            {
                "ManufacturerId": "517863",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "AWMA002",
                "ItemDescription": "SonarMed Monitor Mounting Brac",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "517863",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "AWS030",
                "ItemDescription": "Neonatal SonarMed Sensor - 3.0",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "517863",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "AWS040",
                "ItemDescription": "NEONATAL SONARMED SENSOR 4.0MM PK/5",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "517863",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "AWS0004",
                "ItemDescription": "SENSOR AIRWAVE NEONATE 2.5MM",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "517863",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "AWS0005",
                "ItemDescription": "SENSOR AIRWAVE NEONATE 3.0MM",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ProductCategory": "Angiographic catheter, single-use",
                "gmdnPTDefinition": "A thin, flexible tube designed to inject a contrast medium into select blood vessels of the cerebral, visceral, or peripheral vasculature during an angiographic procedure in order to facilitate the clear visualization of the vascular system of a targeted organ or area of the body. It is introduced percutaneously, has a radiopaque marker(s) for positioning, and may include disposable devices dedicated to catheter introduction/function [e.g., sheath(s)]. It may also be used for simultaneous pressure measurements to determine the transvalvular, intravascular, and intraventricular pressure gradients. This is a single-use device.",
                "ProductFamily": "SiteSeer\u2122",
                "ManufacturerCatalogNumber": "4A0001",
                "companyName": "MEDTRONIC, INC.",
                "ItemDescription": "CATHETER 4A0001 SS 5PK 4F JR 3.5 100CM",
                "productCode": "DQO",
                "productCodeName": "CATHETER, INTRAVASCULAR, DIAGNOSTIC",
                "Model": "4A0001"
            },
            {
                "ProductCategory": "Angiographic catheter, single-use",
                "gmdnPTDefinition": "A thin, flexible tube designed to inject a contrast medium into select blood vessels of the cerebral, visceral, or peripheral vasculature during an angiographic procedure in order to facilitate the clear visualization of the vascular system of a targeted organ or area of the body. It is introduced percutaneously, has a radiopaque marker(s) for positioning, and may include disposable devices dedicated to catheter introduction/function [e.g., sheath(s)]. It may also be used for simultaneous pressure measurements to determine the transvalvular, intravascular, and intraventricular pressure gradients. This is a single-use device.",
                "ProductFamily": "SiteSeer\u2122",
                "ManufacturerCatalogNumber": "4A0001",
                "companyName": "MEDTRONIC, INC.",
                "ItemDescription": "CATHETER 4A0001 SS 5PK 4F JR 3.5 100CM",
                "productCode": "DQO",
                "productCodeName": "CATHETER, INTRAVASCULAR, DIAGNOSTIC",
                "Model": "4A0001"
            },
            {
                "ProductCategory": "Angiographic catheter, single-use",
                "gmdnPTDefinition": "A thin, flexible tube designed to inject a contrast medium into select blood vessels of the cerebral, visceral, or peripheral vasculature during an angiographic procedure in order to facilitate the clear visualization of the vascular system of a targeted organ or area of the body. It is introduced percutaneously, has a radiopaque marker(s) for positioning, and may include disposable devices dedicated to catheter introduction/function [e.g., sheath(s)]. It may also be used for simultaneous pressure measurements to determine the transvalvular, intravascular, and intraventricular pressure gradients. This is a single-use device.",
                "ProductFamily": "SiteSeer\u2122",
                "ManufacturerCatalogNumber": "6A0001",
                "companyName": "MEDTRONIC, INC.",
                "ItemDescription": "CATHETER 6A0001 SS 5PK 6F JR 3.5 100 CM",
                "productCode": "DQO",
                "productCodeName": "CATHETER, INTRAVASCULAR, DIAGNOSTIC",
                "Model": "6A0001"
            },
            {
                "ProductCategory": "Angiographic catheter, single-use",
                "gmdnPTDefinition": "A thin, flexible tube designed to inject a contrast medium into select blood vessels of the cerebral, visceral, or peripheral vasculature during an angiographic procedure in order to facilitate the clear visualization of the vascular system of a targeted organ or area of the body. It is introduced percutaneously, has a radiopaque marker(s) for positioning, and may include disposable devices dedicated to catheter introduction/function [e.g., sheath(s)]. It may also be used for simultaneous pressure measurements to determine the transvalvular, intravascular, and intraventricular pressure gradients. This is a single-use device.",
                "ProductFamily": "SiteSeer\u2122",
                "ManufacturerCatalogNumber": "6A0001",
                "companyName": "MEDTRONIC, INC.",
                "ItemDescription": "CATHETER 6A0001 SS 5PK 6F JR 3.5 100 CM",
                "productCode": "DQO",
                "productCodeName": "CATHETER, INTRAVASCULAR, DIAGNOSTIC",
                "Model": "6A0001"
            },
            {
                "ProductCategory": "Angiographic catheter, single-use",
                "gmdnPTDefinition": "A thin, flexible tube designed to inject a contrast medium into select blood vessels of the cerebral, visceral, or peripheral vasculature during an angiographic procedure in order to facilitate the clear visualization of the vascular system of a targeted organ or area of the body. It is introduced percutaneously, has a radiopaque marker(s) for positioning, and may include disposable devices dedicated to catheter introduction/function [e.g., sheath(s)]. It may also be used for simultaneous pressure measurements to determine the transvalvular, intravascular, and intraventricular pressure gradients. This is a single-use device.",
                "ProductFamily": "SiteSeer\u2122",
                "ManufacturerCatalogNumber": "5A0001",
                "companyName": "MEDTRONIC, INC.",
                "ItemDescription": "CATHETER 5A0001 SS 5PK 5F JR 3.5 100 CM",
                "productCode": "DQO",
                "productCodeName": "CATHETER, INTRAVASCULAR, DIAGNOSTIC",
                "Model": "5A0001"
            }
        ],
        "{'ManufacturerCatalogNumber': 'LXMJ23L', 'ItemDescription': 'Medtronic Minimally Invasive - LXMJ23L'}": [
            {
                "ManufacturerId": "517863",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "XM823",
                "ItemDescription": "SUTURE ABSORBABLE SIZE 4/0 L18IN NEEDLE L19MM DX-19 NATURAL GLYCOLIDE DIOXANONE TRIMETHYLENE CARBONATE 3/8 CIRCLE SINGLE ARMED PREMIUM X CUTTING NEEDLE MONOFILAMENT SYNTHETIC WITHOUT PLEDGET BIOSYN",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "517863",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "LXMJ44L",
                "ItemDescription": "LIGASURE XP MARYLAND 44 CM",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "517863",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "XM823",
                "ItemDescription": "SUT BIOSYN 4-0 DX19",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "517863",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "LXMJ37S",
                "ItemDescription": "Sealer/Divider, Nano, 5 mm \u2014 37 cm",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            },
            {
                "ManufacturerId": "517863",
                "Ticker": "MDT",
                "ManufacturerCatalogNumber": "LXMJ37L",
                "ItemDescription": "SEALER DIVIDER LATCH HANDLE",
                "StandardItemDesc": null,
                "md5checksome": null,
                "Company": "Medtronic",
                "Group": "Other",
                "Business": "Other",
                "Division": "Other",
                "Therapy": "Other",
                "Specialty": "Other",
                "Anatomy": "Other",
                "SubAnatomy": "Other",
                "ProductCategory": "Other",
                "ProductFamily": "Other",
                "Model": "-"
            }
        ]
    }
}